### ISSUE TITLE
Controller Methods for Landlord and Referral Agency

### ISSUE THREAD

**Issue by arpanpal** [calblueprint/HomePointrCIC#14]
_**First generate a controller class for Landlord and controller for Referral Agency**_

**Landlord Controller methods:**

- Create: basic create and save to databases

- Show: basic loading of a specific landlord and show all of their fields underneath i.e. all of their properties and their name, email, address etc. (make sure they are signed in using devise's user_signed_in method)

- Update: should be able to update a record based on params sent in a URL (make sure they are signed in)

- Delete: Deletes a landlord from the database (used by HomePointr for landlord's that aren't verified by their database)

**Referral Agency Controller methods:**

- Create: basic create and save to databases

- Show: basic loading of a specific Referral and show all of their fields underneath i.e. all of their HVIs and their name, email, address etc. Don't worry about sorting the HVIs right now (make sure they are signed in)

- Update: should be able to update a record based on params sent in a URL (make sure the referral agency is signed in before you show this)

- Delete: Deletes a Referral Agency from the database (used by HomePointr for Referral Agencies that aren't verified by their database)

**How do you test this?** 

1. Can create a basic form (.html.erb file) in the views folder so you can test if you are hitting these methods. This might involve creating a route! 
2. Additionally, you can just render a json of the data and verify that it shows up correctly; you will still probably have to set up a route for this too! This is the way we will pass our data from the backend to the frontend so it might prove to be a cooler exercise! 

**Extras:**
**Validations**  - you should be making a "validation" on the controller side for the creation of both (as in you should not allow people to create a user unless they have all of the necessary params (email, name, password, id, etc.) using strong params

Read this for strong params:
https://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters

**More references:**

https://guides.rubyonrails.org/action_controller_overview.html

Any past blueprint project should suffice, but I like the way dream did it:
https://github.com/calblueprint/dream-rails/blob/master/app/controllers/api/attendances_controller.rb

for routes: https://guides.rubyonrails.org/routing.html

**Comment by aliceyezhao** [comment]
In the LL controller and views I tried to account for what should happen if there was a malfunction in the database. However I am not sure if this is the correct approach (so I didn't do it for RA). An @error boolean seems unfitting.
