### ISSUE TITLE
Pending Apps/Your Clients (Property Page)

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#144]
![image](https://user-images.githubusercontent.com/22403821/55533815-605f7680-5667-11e9-8f6f-35b566ba0bcb.png)

![image](https://user-images.githubusercontent.com/22403821/55533823-648b9400-5667-11e9-9832-bca6ef2e2c0d.png)

**Comment by adowski** [comment]
this is done!
