### ISSUE TITLE
CanCanCan

### ISSUE THREAD

**Issue by arpanpal** [calblueprint/HomePointrCIC#15]
Aha it is finally here! We have to make sure the right types of users can see the right kinds of pages 

Read this p thoroughly:https://github.com/ryanb/cancan

We need to set up roles for each type of user! 

If you are a **referral agency** you should be able to: 
1. _read_ all properties
2. _read/edit_ only the hvi's that are associated with you
3. _read/update/create/edit_ all of the applications and info associated with an hvi!
4. _read_ all landlords

If you are a **Landlord**, you should be able to:

1. _edit/read_ only properties associated with you
2. _read_ all hvi's who have _**applied**_ to you (don't worry about hiding sensitive information like SSN quite yet) (hide the hvi's whose status is hidden based off our special status method)! 
3. _read_ the information of a referral agency that have applied to you! 
4. _update/read_ applications with the hvi's that have applied to you. What can landlords update on an application? Only their status. That means that you must also create a model + controller method that only updates the status. Through cancan you will create a custom role that is only allowed to read and do this custom role that is a "status_updater". We can enforce the hidden capabilities of an application (block applications based off of the status of the HVI associated with you) on this level as well.

This should be pretty helpful:
https://github.com/calblueprint/RMI/blob/master/app/models/ability.rb
https://github.com/calblueprint/RMI/blob/master/app/controllers/application_controller.rb

**Comment by deguzmankevin** [comment]
hey
