### ISSUE TITLE
[NEW FEATURE] - Add QuestionMark Modal

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#189]
- Feedback said our application process was not as intuitive as we thought. We should create this page before we start our application process (just to give a review of the process before the user begins)

(this page will be a static component so get rid of the buttons and checkpoint icons)
![image](https://user-images.githubusercontent.com/22403821/56476680-d4b05d00-6450-11e9-9bf7-f605e008d14a.png)

**Comment by wilsonw926** [comment]
Add Question Mark Modal to provide additional help that explains the application process.

**Comment by c4554ndr4** [comment]
This needs to be styled.
