### ISSUE TITLE
[Property Forms]

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#192]
- address autocomplete off click must hide
- make note that the max capacity, bedrooms, etc. is (i.e. max 100)
~~- convert Rent in property, floor, and capacity to integer~~
~~- Error messages use "input" (please "input" a floor number)~~ -CAT
~~- EDIT FORM (Delete Property not Delete Client)~~ -CAT
~~- Render warning for deleting property~~ -MEL
~~- added a "(required)" in the headings i.e. "Step 1: blah (Required)"~~
~~- more bolded Titles (Step 1 blah blah...)~~ - CAT
~~- Create forms need stars to indicate what should be filled out~~
~~- Rent should specify this is monthly~~ - CAT
~~- Photos (state in section that they are optional but encouraged)~~ - CAT

<br />

~~- file checking for pdfs (make sure you can't upload jpgs for example)~~ -MADE NEW ISSUE
~~- Upload image on property new page not rendering~~ (#226)
~~- form upload on property new page also not rendering~~ (#226)

<br />

~~- when there are errors in the edit form, show an error modal that says yo there's a problem couldn't save the property~~ -CAT

<br />

~~- Housing type and property type fields should have information icons to tell users the difference between these two fields (we should add information icons to each field)~~ - CAT

**Comment by melodywei861016** [comment]
I am making the warning for deleting a property

**Comment by melodywei861016** [comment]
@wilsonw926 do we need stars for fields since isn't everything required? that's why we got rid of the stars

**Comment by wilsonw926** [comment]
@melodywei861016 let's added a "(required)" in the headings then "Step 1: blah (Required)"
