### ISSUE TITLE
[Client Forms]

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#194]
~~Client creation form Headers top padding/margin needs to be fixed (header is obscured by the nav bar)~~ (Fixed Melody #209)
~~Slider for rent needs to be auto set with input (min and max, min < max check)~~ (Fixed Melody #209)
~~- Household income should be integer~~ (Fixed Melody)

</br>

~~We forgot some fields in our create form (Ex-offender?, Status of Local Council, etc.). Hence some fields are empty upon loading page tenant edit. Empty fields show below:~~
(FIXED #209 Melody)

</br>

- same feedback as the property creation form, e.g. “rent”, avatar photo preview, etc.
(SEE #192)

~~- Render warning for deleting client~~ (Fixed Melody)

**Comment by melodywei861016** [comment]
I am making the warning for deleting client
