### ISSUE TITLE
Add Property Name

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#195]
- add name to property (rails migration)
- add this field into our form.
- Go through our app and render the name accordingly throughout our app. (also note to add name as a new field when we make PATCH requests, POST requests, etc.)

</br>

INCLUDES: adding field to model, adding field to edit/creation forms, replacing “Eventual Name” instances on PropertyCard with actual name, replacing PropertyShow with name

**Comment by c4554ndr4** [comment]
Splice address' instead so that only the street name and building number is displayed

**Comment by c4554ndr4** [comment]
Also property modals need to have names.

**Comment by c4554ndr4** [comment]
This needs styling now
For the modals the name was supposed to be superimposed on the images.
I'm not sure if the names look good on the property view side panel.
