### ISSUE TITLE
Default No "BLANK" Found Image

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#228]
- when there are no clients, properties, etc. we should render a component that says "there are no properties, or whatever" instead of a blank screen.

- no pending apps/no current clients on property show page

**Comment by florencelau** [comment]
Did this for properties. Used https://undraw.co/
![Screen Shot 2019-04-28 at 3 00 31 PM](https://user-images.githubusercontent.com/16376766/56870580-7b06e000-69c6-11e9-8b9e-bafe6fa2269e.png)

**Comment by adowski** [comment]
gonna do it for the other things!! thank u flo
