### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by arpanpal** [calblueprint/HomePointrCIC#47]
Build a filtering component that takes in a set of arrays to filter (properties) and filters based off of the columns for the model (property_type). There should be separate filters for separate columns. Keep the component barebones as we may use it to implement filtering for tenants in the spring.

1. Create a PropertyFilter component that takes in a list of properties and filters them based on the column names. Alice will have updated designs to give you an idea of how this looks. 
2. Create a Wrapper Component called PropertyListWrapper that renders both the filters and the PropertyList. You should send the list of properties to the filter and render the properties based off of the return values of your filter (so your property filter and propertyList may be intertwined in this component) (remember how we pass functions to modify state to and from parents and children). 

Referral Agencies will see the RA _PropertyWrapper_ component in the end then not the Properties List. Landlords may see a modified version of this in the future, but for now we won't support filtering for them

**Comment by wilsonw926** [comment]
@florencelau @deguzmankevin can i close this?
