### ISSUE TITLE
(Application Process) - Apply to All Button

### ISSUE THREAD

**Issue by arpanpal** [calblueprint/HomePointrCIC#48]
We should be able to create and edit an Application on the front-end. This entails:

Wilson:

1. Create a "Apply button" which loads up a modal (pop-up screen that overlays) that asks them to verify their information (include a cancel button in the modal) under the application and takes in a description. This would mean we have the ability to "select" multiple properties when listed under a tenant's potential applications (some sort of check box that would be added onto Flo and Kevin's property List component when rendered through the Referral Agency View).

2. This modal should have a button that says "Apply to All", as the designs specify, so that they can send an application to each of the Properties that were checked off! 

3. This should trigger an email response that sends an application as well as loads it in the database. Now, a landlord should be able to see applications under their property. This list of applications view will be tricky.

**Comment by wilsonw926** [comment]
TODO: Apply to All Button
