### ISSUE TITLE
Errors/Revamp Profile Forms

### ISSUE THREAD

**Issue by wilsonw926** [calblueprint/HomePointrCIC#97]
Render errors to show up on page and don't crash app.

**Comment by deguzmankevin** [comment]
yeah haha it would be really bad if the app crashed

**Comment by aliceyezhao** [comment]
does pushing to master fix this?

**Comment by ukyerdua** [comment]
seems kinda unfortunate i think pushing to master would work

**Comment by wilsonw926** [comment]
i hate yall

**Comment by wilsonw926** [comment]
See Error Message: 
https://ant.design/components/message/
